const db={
  1:{ question: "How many days do we have in a week?", answer:"Seven"},
  2:{ question: "How many days are there in a normal year?", answer:"365 (not a leap year"},
  3:{ question: "How many colors are there in a rainbow?", answer:"7"},
  4:{ question: "Which animal is known as the Ship of the Desert?", answer:"Camel"},
  5:{ question: "How many letters are there in the English alphabet?", answer:"26"},
  6:{ question: "How many consonants are there in the English alphabet?", answer:"21"},
  7:{ question: "How many sides are there in a triangle?", answe:"three"},
  8:{ question: "Which month of the year has the least number of days?", answer:"February"},
  9:{ question: "Which are the vowels in the English alphabet series?", answer:"A,E,I,O,U"},
  10:{ question: "Which animal is called King of Jungle?", answer:"Lion"},
  11:{ question: "In which direction does the sunrise?", answer:"East"},
  12:{ question: "Which is the world’s largest flower?", answer:"Rafflesia"},
  13:{ question: "How many zeros are there in one hundred thousand?", answer:"five"},
  14:{ question: "How many zeros are there in one hundred thousand?", answer:"48hours"},
  15:{ question: "How many months of the year have 31 days?", answer:"7"},
  16:{ question: "How many weeks are there in one year?", answer:"52"},
  17:{ question: "Which are the colors in a rainbow?", answer:"Violet, Indigo, Blue, Green, Yellow, Orange, Red"},
  18:{ question: "How many bones does an adult human have?", answer:"206"},
  19:{ question: "Who was the first man to walk on the moon?", answer:"Neil Armstrong"},
  20:{ question: "How many millimeters are there in 1cm?", answer:"10"},
  21:{ question: "What do you call a type of shape that has five sides?",answer:"pentagon"},
  22:{ question: "Which way is anti-clockwise, left or right?", answer:"left"},
  23:{ question: "How many equal sides does an isosceles triangle have?", answer:"2"},
  24:{ question: "Which is the coldest location in the earth?", answer:"East Antarctica"},
  25:{ question: "Who discovered electricity?", answer:"Benjamin Franklin"},
  26:{ question: "Which is the most widely spoken language in the world?",answer:"Chinese"},
  27:{ question: "Which two parts of the body continue to grow for your entire life?", answer:"nose and ears"},
  28:{ question: "The largest ‘Democracy’ in the world?", answer:"India"},
  29:{ question: "Who is the inventor of Television?", answer:"John Logie Baird"},
  30:{ question: "Which is the largest plateau in the world?", answer:"Tibetan Plateau"}
};